version: '3'
services:
    web:
        #image: tiangolo/uwsgi-nginx-flask:python3.7        
        build: .
        ports:
            - "5000:80"        
        restart: always
        environment:
            - IMAGES_PATH=/var/www/visionlabs_test_task/images
            - UWSGI_INI=/visionlabs_test_task/uwsgi.ini        